server:
  port: 8081
  
spring:
  application:
    name: 'arrecadacao'
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888/  
            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka    
